### ISSUE TITLE
Scope out opportunities to simplify aind-data-schema

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#1056]

**Comment by dbirman** [comment]
Some notes from poking around. This will be an ongoing comment:

acquisition.py
- ProcessingSteps probably needs to be generalized for outside users, potentially moved out of this file

data_description.py
- platform is currently internal
- organizations list is pretty limited for outside users
-

**Comment by dbirman** [comment]
Blocking this until next meeting about it

**Comment by dbirman** [comment]
1st discussion about specific changes (9/27)

Simplifying procedures
- Put them into a components file
- Subject/Specimen procedures in different component files

Coordinates [breaking change]
- There should be a SurgeryCoordinates class? List[that]
- Attach angles
- Atlas + transforms

Extensions
- Make an extensions/aind/??

Instrument
- Calibrations are deprecated, remove? Or replace with devices.Calibration. Talk to John + Adam

Value with Unit [breaking change]
- Replaced them all with value and value_unit
- Remove all XValue and take them out of models repo

Rig [breaking change]
- Annotated Union instead of list of Optional

**Comment by dbirman** [comment]
Idea: "people" should be abstracted out so that we're re-using the same class and set of information across all mentions of people? (e.g. evaluator in qc, and experimenter in other places)

**Comment by saskiad** [comment]
- Use annotated unions in rig and session to remove empty lists that confuse users.
- create AIND specific validators in an AIND extension so WE can require fields that we don't expect external scientists to have.
- remove the stimulus classes. These can maybe be in an extension. The goal really is for people to create their own dictionary that is consistent to a project/platform/whatever the right level is, but not for us to dictate or maintain those. (We might need to develop some tools to help people do this though)
-

**Comment by dbirman** [comment]
Simplifications are going to be moved to a spec doc https://alleninstitute.sharepoint.com/:w:/r/sites/NeuralDynamics/_layouts/15/Doc.aspx?sourcedoc=%7BE27B889D-27A1-4CC0-948C-10ADBE605654%7D&file=Data+Schema+2.0.docx&action=default&mobileredirect=true where we can continue the discussion, before breaking these out into tickets
