### ISSUE TITLE
Add asset_id to QCEvaluation

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-data-schema#1088]

**Comment by saskiad** [comment]
I left comments in some of the PRs, but I have a few concerns about having asset_id in the evaluation.

First, there's no concept of asset_id in the rest of the schema. If the evaluation every points to a different asset (e.g. the parent raw asset for a derived asset), this id won't communicate that that's where it's pointing to. 
If it's always pointing only to the asset_id of THIS asset, then I'm not sure it's needed. E.g. it might be something needed in the QC portal to route the evaluation, but doesn't need to be in the evaluation.
I mostly think that it will be confusing, because it's not anywhere else in the schema. Even using the asset name would be better since that is in the schema.
