### ISSUE TITLE
process names inconsistent

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#119]
https://github.com/AllenNeuralDynamics/aind-data-schema/blob/80305cd17ac9d1b39d73cae744878456db34c736/src/aind_data_schema/processing.py#L13

These are a combination of specific algorithms (e.g. pystripe) and kinds of processing steps (e.g. ephys preprocessing).  We should pick one.  I recommend the latter (general names of processing stages).

**Comment by dyf** [comment]
@saskiad if you are okay with my proposal I can take this.

**Comment by saskiad** [comment]
hmm... I actually worry about the general names as they can be vague and could easily morph. Eg. ephys preprocessing encompasses several different steps. Perhaps that's not an issue if the specific algorithms are named within the process?

**Comment by saskiad** [comment]
hmm... I actually worry about the general names as they can be vague and could easily morph. Eg. ephys preprocessing encompasses several different steps. Perhaps that's not an issue if the specific algorithms are named within the process?

**Comment by camilolaiton** [comment]
Hello @dyf @saskiad, I've been adding data processes to our scripts and I recommend we have the following names for processes:

- Image projection
- Image threshold
- Image placing tiles

Also, I recommend we change the name 'Displthresh' for 'Image thresholding' which is more descriptive. Finally, I feel we should keep the process names general since we have the **_code_url_** and **_parameters_** attributes that points to the used algorithm.

Please, consider this proposal. Thanks.
