### ISSUE TITLE
request: do not include version in rig ID

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#126]
Reasoning from ephys team - this will be hard to do correctly, should be handled automatically if at all.

Proposal:
- let rig ID autoincrement in the SLIMS, add a separate `rig_name` field that is not versioned.

**Comment by saskiad** [comment]
we should address this sooner rather than later. The current system is room number_behavior apparatus_version. I think we need the version to indicate when components have changes. This can be done automatically if we can figure that out, but I think having the same rig id when the components are different is a problem.
We also need to actually use this system, because the current room number_EPHYS means that there are different behavior/stim apparatus, which imo are not the same rig.

**Comment by mekhlakapoor** [comment]
@saskiad @dyf I saw that this was already added and then removed from our project board. Should we transfer this to discussions?

**Comment by saskiad** [comment]
I think we can delete this, the discussion has already been had

**Comment by mekhlakapoor** [comment]
This has already been discussed.
