### ISSUE TITLE
Duration fields should use `timedelta`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#223]
@saskiad @mekhlakapoor The duration fields in the pydantic models should probably be `timedelta` types, which is python's equivalent of Java's Duration class. The `time` class is supposed to represent a time of day, which has hard limits like hour < 24 etc. We can also avoid writing workarounds like the ones in the utils package here.

_Originally posted by @jtyoung84 in https://github.com/AllenNeuralDynamics/aind-metadata-service/pull/82#pullrequestreview-1346288332_

**Comment by jtyoung84** [comment]
> does this require start/end times be reported? I think the duration field we have (and @mekhlakapoor can correct me if I'm wrong here) are provided in the SWR as durations, rather than start/end times. Or is it just a different type of time unit?

We can use the reported durations. The issue is that we're converting the durations into a `time` object instead of a `timedelta` object. This can cause issues in the future. For example, if the duration lasted more than a day, then the `time` object would raise an error because it's expected to be less than 24 hours.
