### ISSUE TITLE
update aind_data_schema.__init__ to include imports for newer classes

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#310]
__init__ file hasn't been updated in a while, and could use some attention.

At this moment missing newer classes like BehaviorRig, BehaviorSession, OphysRig, OphysSession.

Interest in what convention should be utilized for knowing which modules need to be imported within __init__.

Current rules seem to be:
- All classes that utilize AindCoreModel
- All classes that inherirt classes utilizing AindCoreModel
- Some classes utilizing AindModel (but not all, this could just be due to lack of updating)

@saskiad @dyf @jtyoung84 might be able to clarify ideal guidelines here.

**Comment by dyf** [comment]
@Sun-flow @saskiad This was done ad-hoc at the beginning, open to discussion for how to proceed moving forward. I see two options that might make sense:

1. All `AindCoreModel` classes
2. Don't import anything - have people use fully qualified imports. (e.g. `from aind_data_schema.ephys.ephys_session import EphysSession` instead of  `from aind_data_schema import EphysSession`.

I think I prefer (2).  You can't actually make an `EphysSession` without importing a bunch of other stuff, and the fact that we have things that share a name in session/acquisition and rig/instrument makes it hard to just globally import things.

**Comment by jtyoung84** [comment]
> @Sun-flow @saskiad This was done ad-hoc at the beginning, open to discussion for how to proceed moving forward. I see two options that might make sense:
> 
> 1. All `AindCoreModel` classes
> 2. Don't import anything - have people use fully qualified imports. (e.g. `from aind_data_schema.ephys.ephys_session import EphysSession` instead of  `from aind_data_schema import EphysSession`.
> 
> I think I prefer (2). You can't actually make an `EphysSession` without importing a bunch of other stuff, and the fact that we have things that share a name in session/acquisition and rig/instrument makes it hard to just globally import things.

I like the idea of (2) also. We might want to mark the list as deprecated instead of deleting it. We should also write a utility function that uses inspection to return all the model classes.

**Comment by Sun-flow** [comment]
> We should also write a utility function that uses inspection to return all the model classes.

All models in the whole aind_data_schema, or all models currently imported? If it's the latter, I have written this already for the ERD diagrams.

**Comment by saskiad** [comment]
I agree with (2).

And I'd say all models that are AindCoreModel, but I guess it depends on when all we'd use the utility function.

**Comment by jtyoung84** [comment]
- [ ] Remove everything except the version number from the init file

**Comment by jtyoung84** [comment]
This was closed via the pydantic v2 upgrade
