### ISSUE TITLE
Figure out why ConstrainedListValues aren't diagrammed in erdantic

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#325]
Some of the diagrams are pretty inaccurate because erdantic doesn't show the ConstrainedListValues. Eg. Procedures. I can't figure out what is different about the classes that are called "ConstrainedListValues" and the ones that are a "List".

**Comment by jtyoung84** [comment]
@saskiad The "ConstrainedListValue" shows up in lists where the Field has the unique_items attribute set to True. This is probably related to this bug in pydantic: https://github.com/pydantic/pydantic/issues/3765
Supposedly, this is fixed in v2 of pydantic scheduled to be released in 2023 Q3, but I tested out the v2-alpha and it causes issues with erdantic. It appears that v1 pydantic is overwriting the annotations needed for erdantic to generate the diagrams correctly, so this could be a tricky bug to fix.

**Comment by saskiad** [comment]
Should we consider removing the unique_items attribute? I never know how important things like that are

**Comment by jtyoung84** [comment]
I'd recommend keeping it if we want to validate/enforce whether items in a list are unique. It might be worthwhile to double-check if we want that in all the Fields where it's being set to True. For this erdantic bug, we can open an issue in that library to see if they might be willing to add fix it on their end.

**Comment by jtyoung84** [comment]
I added a ticket to the erdantic repo: https://github.com/drivendataorg/erdantic/issues/81

**Comment by saskiad** [comment]
Thanks @jtyoung84

**Comment by jtyoung84** [comment]
This should no longer be an issue when upgrading to pydantic 2.0
