### ISSUE TITLE
Differences with similar devices between Imaging/EPhys

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#511]
This might not be needed or worth the effort, but I recently noticed there are similar devices defined differently between Imaging and EPhys instruments/rigs.

1. EPhys instrument has a ```Lens``` whereas this is not present in the imaging schema. I am adding them in as additional imaging devices, but would prefer to inherit Lens definition from Ephys.
2. EPhys has a ```Camera``` whereas for Imaging we are using ```Detector```.  Again here does it make sense to update Imaging with the Camera definition from Ephys?
3. Same for ```Laser``` in Ephys and the current ```Lightsource``` in Imaging.

**Comment by saskiad** [comment]
Yeah, this has come up a couple times. I'll work to integrate these.

**Comment by adamkglaser** [comment]
That sounds good, thanks!

**Comment by saskiad** [comment]
@adamkglaser a couple notes - we actually just started deprecating the ephys rig schema as we've made a single ephys/ophys/behavior rig. So I've moved a lot of the classes from ephys and ophys into device. 
But on the whole, I agree we should try to use the same classes and not redefine things in the Instrument schema.

I propose:
1. import lens from device
2. would you prefer to use the Camera or the Detector class that is in Device - we definitely should inherit one of these from device rather than have a separate class in instrument. I think we have a separate issue open about potentially making camera more like detector overall - so they might get merged. But I think detector makes more sense for use in Instrument, no?
3. We could definitely have Instrument import both laser and LED and have the lightsource be a union of the two (as it is for rig). I think the question is how do we represent Lamp. I believe we added that for the slide scanner(?). I could maybe just make a lamp class for that as well, and then it's a union of the three.


How does this sound?

**Comment by adamkglaser** [comment]
Thanks this all makes sense.

1. Agreed!
2. Also agreed, I just took a look at Camera and Detector and it looks like Detector has everything, perhaps we just add the optional fields ```sensor_width: int = Field(..., title="Width of the sensor in pixels", units="Pixels")``` and ```sensor_height: int = Field(..., title="Height of the sensor in pixels", units="Pixels")```? In addition to the ```bin``` and ```crop``` width and heights.
3. Agreed about importing both laser and LED. And we could create a ```Lamp``` class in device. Others might have input, but for lamps, because they are not monochromatic and have broad spectra, I think we would want to specify ```wavelength_min``` and ```wavelength_max``` to specify the spectral range. And perhaps an optional field of ```temperature``` with units of Kelvin which adds a little more detail on top of the min/max fields.
