### ISSUE TITLE
No more duplicated model/class names

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#531]
Right now, we have multiple classes with the same name because Device and Device configuration models are both named the same. This is confusing.

Proposal: rename Session and Acquisition classes to "<x>Config". Then we would have a `Laser` device in used in a `Rig`, and a `LaserConfig` used in a `Session`.

**Comment by bruno-f-cruz** [comment]
This should not be a problem when defining the classes in pydantic, if i understand correctly? Since they could, in theory, have different namespaces (i.e. modules). This will however be a problem when serializing/deserializing as JSON which, as opposed to XML, does not have the concept of namespaces. Would it be a good idea to add a new field to the aforementioned objects that establish a namespace when serialized (ie. which module do they come from)?

**Comment by dyf** [comment]
@bruno-f-cruz They are different concepts, so they should have different names. Better to fix the root problem.

**Comment by jtyoung84** [comment]
Should be closed by https://github.com/AllenNeuralDynamics/aind-data-schema/pull/608
