### ISSUE TITLE
Olfactometer

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#615]
new device:
- [ ] 5 channels: carrier channel + 4 odor channels
- [ ] channel type (odor/carrier)
- [ ] each channel has a flow_range (unit = mL/min)
- [ ] odor vial volume and odorant volume

add as a stimulus device in rig

In session:
- [ ] per channel: odor identity. dilution (what are units?). (flow rate is stimulus data, not metadta)

@bruno-f-cruz am I missing something here?

**Comment by bruno-f-cruz** [comment]
Olfactometer should inherit from Harp Device. Otherwise looks fine.

Per session, I completely agree that flow rate is data (we are already saving it). 
Odor Identity should be a string
Odor dilution. I am not sure about this, there are probably several ways to express an odor dilution, not sure if we should accept them all or converge on a single one.
Here's an example:
 Cindy suggests using %(V/V) (i.e. ml_odor / 100ml of solvent). However this creates a situation where the experimenter also needs to express the absolute concentration of the stock solution used for the dilution (probably in molar concentration). The solvent solution should also be represented somehow. The alternative could be to express it in %(W/V) (mg of solute per ml of solvent), but once again you need to keep track of the solvent identity. So my question is: How much information do you expect to be able to recover from the metadata field? If it is just a qualitative metric, then leaving it at a `float` is probably sufficient, and then people will need to document what that number means down the road, if it you want have something that can fully express a dilution, you might want to go ahead and implement a dilution class that is able to express such dilution.
