### ISSUE TITLE
Modality: remove "trained behavior" and replace with "head-fixed behavior" and "Freely moving behavior"

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#623]
### Discussed in https://github.com/AllenNeuralDynamics/aind-data-schema/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **saskiad** November 21, 2023</sup>
We currently have modalities of "Behavior videos" and "Trained Behavior." We are preparing for open field, untrained behavior (eg. motor observatory). 
Should we have a modality of "Open field behavior" in which case should we replace "trained behavior" with "headfixed behavior"? 
Should we have a modality of "exploratory behavior" or "free behavior" or "untrained behavior" and then add a field somewhere to indicate "headfixed" vs "open field"?
Other ideas? @dyf @bruno-f-cruz</div>

**Comment by bruno-f-cruz** [comment]
I tend to agree with @dyf. I think the problem is actually the behavior videos. If you don't want to refactor, I would favor "Operant Behavior" over "Trained Behavior"

**Comment by saskiad** [comment]
So what do you all want to call behavior videos then?

**Comment by saskiad** [comment]
and do you want to not distinguish between head fixed and freely moving behavior? This has been asked for by scientists and I think is valuable, but am also fine not using the modality to distinguish it.

**Comment by bruno-f-cruz** [comment]
I think it goes back to the current definition of `Modality` that I confess I struggle a bit with. I don't necessarily see why Behavior_Videos should be above any other data stream produced by the animals' "Behavior". I don't see the conceptual difference between a video and the output of a sensor, say some load cell measuring the force the animal applies on something.

Re: headfix vs freely moving, isn't this redundant with the platform being used? i.e. cant I just query the existence of a platform to know what sort of behavior it is? If it is just for convenience I would add it to the array of modalities. For instance a certain stream can be : [OperantBehavior, HeadfixBehavior] instead of [Operant_HeadfixBehavior]

**Comment by saskiad** [comment]
> I don't see the conceptual difference between a video and the output of a sensor, say some load cell measuring the force the animal applies on something.

Agreed. I think the issue is that a lot of data without a behavioral task that include behavioral videos. When this is referred to as "behavior" then people are confused because they are expecting a task or some active component. This distinguishes between the passive behavior and active behavior paradigms.
