### ISSUE TITLE
Automate schema version increments 

### ISSUE THREAD

**Issue by yosefmaru** [AllenNeuralDynamics/aind-data-schema#735]
# User story
As a developer, I want to automate schema version increments, so I don't have to do them manually

# Acceptance criteria
- [ ] When a PR is merged to main, a workflow job has to increment the necessary schema versions
- [ ] Configure the github repo to queue PRs
- [ ] Increment patch by default.
- [ ] (stretch) Workflows to increment minor and major versions.
 
# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
Maybe queue PR merges if more than one PR is requested simultaneously

**Comment by bruno-f-cruz** [comment]
Looking at the current pipeline I am also wondering what happens if a change is made to the pydantic model that does not result in a change in the json-schema. I guess the question is: what is being version? is it the pydantic models or the json-model that results from it?

If the latter, I suggest adopting a strategy wherein on each merge to main, all schemas are re-generated and compared. If a diff exists, automatically bump the patch version automatically. Minor and Major should probably be done manually. This strategy would also prevent unnecessary bumping schema model version without modifications to the schema itself.
